# Generated by Django 5.0.6 on 2024-05-27 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('file_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='File Number')),
                ('client_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('deal_type', models.CharField(choices=[('Purchase', 'Purchase'), ('Sale', 'Sale'), ('Refinance', 'Refinance'), ('Will', 'Will'), ('Title Transfer', 'Title Transfer'), ('Refuge', 'Refuge')], max_length=225)),
                ('unit_number', models.IntegerField(default=0)),
                ('street_number', models.IntegerField(default=0)),
                ('street_name', models.CharField(max_length=100)),
                ('street_suffix', models.CharField(choices=[('Avenue', 'Avenue'), ('Road', 'Road'), ('Street', 'Street'), ('Blvd', 'Blvd'), ('Court', 'Court'), ('Cresent', 'Cresent')], max_length=100)),
                ('city', models.CharField(choices=[('Toronto', 'Toronto'), ('Ottawa', 'Ottawa'), ('Mississauga', 'Mississauga'), ('Brampton', 'Brampton'), ('Hamilton', 'Hamilton'), ('London', 'London'), ('Markham', 'Markham'), ('Vaughan', 'Vaughan'), ('Kitchener', 'Kitchener'), ('Richmond Hill', 'Richmond Hill')], max_length=100)),
                ('province', models.CharField(choices=[('ON', 'Ontario'), ('QC', 'Quebec'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('MB', 'Manitoba'), ('AB', 'Alberta'), ('BC', 'British Columbia')], max_length=100)),
                ('closing_year', models.IntegerField(choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028)], default=2001)),
                ('closing_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=5)),
                ('closing_date', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], default=1)),
                ('outstanding', models.TextField()),
                ('dialog', models.TextField()),
                ('is_deal_closed', models.BooleanField(default='No', max_length=100)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
