# Generated by Django 5.0.6 on 2024-06-01 18:07

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('file_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='File Number')),
                ('client_name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('client_photo1', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('client_photo2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('client_photo3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('deal_type', models.TextField(choices=[('Purchase', 'Purchase'), ('Sale', 'Sale'), ('Refinance', 'Refinance'), ('Will', 'Will'), ('Title Transfer', 'Title Transfer'), ('Refuge', 'Refuge')])),
                ('unit_number', models.IntegerField(blank=True, null=True)),
                ('street_number', models.IntegerField(default=0)),
                ('street_name', models.CharField(max_length=100)),
                ('street_suffix', models.CharField(choices=[('Avenue', 'Avenue'), ('Road', 'Road'), ('Street', 'Street'), ('Blvd', 'Blvd'), ('Court', 'Court'), ('Cresent', 'Cresent')], max_length=100)),
                ('city', models.CharField(choices=[('Toronto', 'Toronto'), ('Ottawa', 'Ottawa'), ('Mississauga', 'Mississauga'), ('Brampton', 'Brampton'), ('Hamilton', 'Hamilton'), ('London', 'London'), ('Markham', 'Markham'), ('Vaughan', 'Vaughan'), ('Kitchener', 'Kitchener'), ('Richmond Hill', 'Richmond Hill')], max_length=100)),
                ('province', models.CharField(choices=[('ON', 'Ontario'), ('QC', 'Quebec'), ('NS', 'Nova Scotia'), ('NB', 'New Brunswick'), ('MB', 'Manitoba'), ('AB', 'Alberta'), ('BC', 'British Columbia')], max_length=100)),
                ('final_closing_date', models.DateField()),
                ('outstanding', ckeditor.fields.RichTextField()),
                ('dialog', ckeditor.fields.RichTextField()),
                ('is_deal_closed', models.BooleanField(default='No', max_length=100)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
