# Generated by Django 5.0.6 on 2024-06-01 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='final_closing_date',
        ),
    ]
