# Generated by Django 5.0.6 on 2024-05-30 00:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_client_photo1_transaction_client_photo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='dialog',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='outstanding',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
